version: '3.4'
services:
  nginx-loadbalancer:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'
  express:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_PORT=6379
  redis-server:
    image: redis
volumes:
  nodemodules:
